# generated by datamodel-codegen:
#   filename:  es_result.json
#   timestamp: 2026-02-02T07:28:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class FieldShards(BaseModel):
    total: int
    successful: int
    skipped: int
    failed: int


class Total(BaseModel):
    value: int
    relation: str


class FieldSource(BaseModel):
    id: str
    parent_id: str | None = None
    chunk_type: str | None = None
    content: str | None = None
    name: str | None = None
    quantity: str | None = None
    ingredients: list[str] | None = None
    category: str | None = None
    tags: list[str] | None = None


class Hit(BaseModel):
    field_index: str = Field(..., alias='_index')
    field_id: str = Field(..., alias='_id')
    field_score: float = Field(..., alias='_score')
    field_source: FieldSource = Field(..., alias='_source')


class Hits(BaseModel):
    total: Total
    max_score: float
    hits: list[Hit]


class EsPointsModel(BaseModel):
    took: int
    timed_out: bool
    field_shards: FieldShards = Field(..., alias='_shards')
    hits: Hits
