"""Add speaker column to Source table

Revision ID: 144f0d1ec38d
Revises: ede290e354d4
Create Date: 2026-06-30 13:15:07.837643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144f0d1ec38d'
down_revision: Union[str, Sequence[str], None] = 'ede290e354d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('speaker', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'speaker')
    # ### end Alembic commands ###
