"""Modify field name of Chunk table

Revision ID: 19c56cd1fc41
Revises: b7d44953cacb
Create Date: 2026-07-01 16:42:03.129905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c56cd1fc41'
down_revision: Union[str, Sequence[str], None] = 'b7d44953cacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('speaker', sa.String(), nullable=True))

    # 將 primary_speaker 的值複製到 speaker
    # 使用 SQL 的 UPDATE table SET new_col = old_col 語法
    op.execute("UPDATE chunks SET speaker = primary_speaker")

    op.drop_column('chunks', 'primary_speaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('primary_speaker', sa.VARCHAR(), autoincrement=False, nullable=True))

    # 把資料倒推回去
    op.execute("UPDATE chunks SET primary_speaker = speaker")

    op.drop_column('chunks', 'speaker')
    # ### end Alembic commands ###
