"""Remove recipes chunks table

Revision ID: 1c6ecd14f69d
Revises: a11cb2664aea
Create Date: 2026-06-10 14:52:16.713650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6ecd14f69d'
down_revision: Union[str, Sequence[str], None] = 'a11cb2664aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_chunks',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('chunk_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['recipes.id'], name=op.f('recipe_chunks_parent_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('recipe_chunks_pkey'))
    )
    # ### end Alembic commands ###
