"""Modify column name

Revision ID: 26c58609cc5b
Revises: 4b138b0d5ba6
Create Date: 2026-03-02 10:59:22.429645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c58609cc5b'
down_revision: Union[str, Sequence[str], None] = '4b138b0d5ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('event_id', sa.UUID(), nullable=False))
    op.drop_column('outbox', 'evnet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox', sa.Column('evnet_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('outbox', 'event_id')
    # ### end Alembic commands ###
