"""Add relationship between section and llm_artifacts

Revision ID: 2a858e762b0d
Revises: 440eb3f39b5c
Create Date: 2026-06-26 13:50:52.929564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a858e762b0d'
down_revision: Union[str, Sequence[str], None] = '440eb3f39b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_current_artifact', 'llm_artifacts', ['section_id', 'stage'], unique=True, postgresql_where=sa.text('is_current = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_current_artifact', table_name='llm_artifacts', postgresql_where=sa.text('is_current = true'))
    # ### end Alembic commands ###
