"""add source_url, status, retry, updated_at and last_error column to users

Revision ID: 55481c374fb0
Revises: 44445a8a1018
Create Date: 2026-02-21 16:16:37.188202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55481c374fb0'
down_revision: Union[str, Sequence[str], None] = '44445a8a1018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('recipes', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recipes_source_url'), 'recipes', ['source_url'], unique=True)
    op.create_index(op.f('ix_recipes_status'), 'recipes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_status'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_source_url'), table_name='recipes')
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'last_error')
    op.drop_column('recipes', 'retry_count')
    op.drop_column('recipes', 'status')
    op.drop_column('recipes', 'source_url')
    # ### end Alembic commands ###
