"""Alter Section table the type of cleaned_content

Revision ID: 56b9c2a7a906
Revises: fe41df3afca0
Create Date: 2026-06-17 17:52:26.841632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b9c2a7a906'
down_revision: Union[str, Sequence[str], None] = 'fe41df3afca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'cleaned_content',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='cleaned_content::jsonb',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sections', 'cleaned_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               postgresql_using='cleaned_content::text',
               existing_nullable=True)
    # ### end Alembic commands ###
