"""Add source column to Recipe table

Revision ID: a11cb2664aea
Revises: e71d9a0be77f
Create Date: 2026-06-09 21:46:51.452317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11cb2664aea'
down_revision: Union[str, Sequence[str], None] = 'e71d9a0be77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'source')
    # ### end Alembic commands ###
