"""Remove cleaned_text of the Section table

Revision ID: b7d44953cacb
Revises: 144f0d1ec38d
Create Date: 2026-06-30 22:05:47.692758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d44953cacb'
down_revision: Union[str, Sequence[str], None] = '144f0d1ec38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'cleaned_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('cleaned_content', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
