"""modify table column declaration

Revision ID: bb0543da5ca7
Revises: fdfa3328fc23
Create Date: 2026-05-13 14:35:16.063399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0543da5ca7'
down_revision: Union[str, Sequence[str], None] = 'fdfa3328fc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('recipes', 'source_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('recipes', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('recipes', 'source_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
