"""Add video_id column to Source table

Revision ID: be39b45d53d5
Revises: bbaba5c1b652
Create Date: 2026-06-17 13:53:41.817630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be39b45d53d5'
down_revision: Union[str, Sequence[str], None] = 'bbaba5c1b652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('video_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'video_id')
    # ### end Alembic commands ###
