"""Add description and steps to recipe table

Revision ID: e71d9a0be77f
Revises: bb0543da5ca7
Create Date: 2026-06-07 11:34:45.043474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71d9a0be77f'
down_revision: Union[str, Sequence[str], None] = 'bb0543da5ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('steps', sa.Text(), nullable=True))

    conn = op.get_bind()

    conn.execute(sa.text("""
            UPDATE recipes
            SET description = recipe_chunks.content
            FROM recipe_chunks
            WHERE recipes.id = recipe_chunks.parent_id
              AND recipe_chunks.chunk_type = 'overview'
        """))

    conn.execute(sa.text("""
            UPDATE recipes
            SET steps = recipe_chunks.content
            FROM recipe_chunks
            WHERE recipes.id = recipe_chunks.parent_id
              AND recipe_chunks.chunk_type = 'instruction'
        """))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'steps')
    op.drop_column('recipes', 'description')
    # ### end Alembic commands ###
