"""Modify the fileds of chunks table

Revision ID: ede290e354d4
Revises: 2a858e762b0d
Create Date: 2026-06-29 18:20:51.093235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede290e354d4'
down_revision: Union[str, Sequence[str], None] = '2a858e762b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('question', sa.Text(), nullable=False))
    op.add_column('chunks', sa.Column('answer', sa.Text(), nullable=False))
    op.add_column('chunks', sa.Column('embedding_text', sa.Text(), nullable=False))
    op.add_column('chunks', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('primary_speaker', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('llm_artifact_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('uq_chunk_order'), 'chunks', type_='unique')
    op.create_foreign_key(None, 'chunks', 'llm_artifacts', ['llm_artifact_id'], ['id'])
    op.drop_column('chunks', 'text')
    op.drop_column('chunks', 'order_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_chunk_order'), 'chunks', ['section_id', 'order_index'], postgresql_nulls_not_distinct=False)
    op.drop_column('chunks', 'llm_artifact_id')
    op.drop_column('chunks', 'primary_speaker')
    op.drop_column('chunks', 'topic')
    op.drop_column('chunks', 'embedding_text')
    op.drop_column('chunks', 'answer')
    op.drop_column('chunks', 'question')
    # ### end Alembic commands ###
