"""Set video_id column nullable False

Revision ID: fe41df3afca0
Revises: be39b45d53d5
Create Date: 2026-06-17 13:56:31.170597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe41df3afca0'
down_revision: Union[str, Sequence[str], None] = 'be39b45d53d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'video_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'video_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
