# generated by datamodel-codegen:
#   filename:  detail.json
#   timestamp: 2026-02-14T19:28:46+00:00

from __future__ import annotations

from pydantic import BaseModel


class Ingredient(BaseModel):
    name: str
    amount: str


class SeasoningItem(BaseModel):
    name: str
    amount: str


class Step(BaseModel):
    img: str
    step: str


class TastyNoteRecipe(BaseModel):
    id: str
    source_url: str

    source: str = "tasty-note"
    name: str | None = None
    category: str | None = None
    description: str | None = None
    quantity: str | None = None

    ingredients: list[Ingredient] | None = None
    seasoning: list[SeasoningItem] | None = None
    steps: list[Step] | None = None
    tags: list[str] | None = None
