# generated by datamodel-codegen:
#   filename:  detail.json
#   timestamp: 2026-02-14T19:28:46+00:00

from __future__ import annotations

from pydantic import BaseModel


class Ingredient(BaseModel):
    name: str
    amount: str


class SeasoningItem(BaseModel):
    name: str
    amount: str


class Step(BaseModel):
    img: str
    step: str


class TastyNoteRecipe(BaseModel):
    id: str
    name: str = None
    source_url: str
    category: str = None
    description: str = None
    quantity: str = None
    ingredients: list[Ingredient] = None
    seasoning: list[SeasoningItem] | None = None
    steps: list[Step] = None
    tags: list[str] = None
