# generated by datamodel-codegen:
#   filename:  detail.json
#   timestamp: 2026-02-14T19:28:46+00:00

from __future__ import annotations

from pydantic import BaseModel


class Ingredient(BaseModel):
    name: str
    amount: str


class SeasoningItem(BaseModel):
    name: str
    amount: str


class Step(BaseModel):
    img: str
    step: str


class TastyNoteRecipe(BaseModel):
    id: str
    name: str
    category: str
    description: str
    quantity: str
    ingredients: list[Ingredient]
    seasoning: list[SeasoningItem] | None = None
    steps: list[Step]
    tags: list[str]
